### ISSUE TITLE
Windows Server: `gvfs mount` from a non-elevated prompt can fail after performing an elevated `gvfs clone`

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1115]
See also related issue #1089

**Steps to reproduce:**

1. Install Git and VFS4G on a fresh Server machine
2. In an elevated CMD prompt
```
mkdir C:\Repos
cd C:\Repos
gvfs clone https://gvfs.visualstudio.com/ci/_git/ForTests
cd ForTests
dir
gvfs unmount
```
3. In a non-elevated CMD
```
cd C:\Repos\ForTests
gvfs mount
```

**Observed Results**

*CMD Window*

```
C:\Repos\ForTests>gvfs mount
Attaching ProjFS to volume...Succeeded
Authenticating...Succeeded
Querying remote for config...Succeeded
Configured cache server: None (https://gvfs.visualstudio.com/ci/_git/ForTests)
Validating repo...Succeeded
Mounting...Failed. Run 'gvfs log C:\Repos\ForTests' for more info.
Could not connect to GVFS.Mount: GVFS.Common.NamedPipes.BrokenPipeException: Unable to send: GetStatus ---> System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at GVFS.Common.NamedPipes.NamedPipeStreamWriter.WriteMessage(String message)
   at GVFS.Common.NamedPipes.NamedPipeClient.SendRequest(String message)
   --- End of inner exception stack trace ---
   at GVFS.Common.NamedPipes.NamedPipeClient.SendRequest(String message)
   at GVFS.Common.GVFSEnlistment.WaitUntilMounted(String enlistmentRoot, Boolean unattended, String& errorMessage)
```

*Mount Log*

```
[2019-05-06 16:32:12 -07:00] GVFSMount (Start) {"Version":"1.0.19116.1","EnlistmentRoot":"C:\\Repos\\ForTests","Remote":"https://gvfs.visualstudio.com/ci/_git/ForTests","ObjectsEndpoint":"https://gvfs.visualstudio.com/ci/_git/ForTests","IsElevated":false,"EnlistmentRootPathParameter":"C:\\Repos\\ForTests","StartedByService":"False"}
[2019-05-06 16:32:13 -07:00] RetryConfig_LoadedRetryConfig {"Area":"RetryConfig","Timeout":"00:00:30","MaxRetries":6,"Message":"RetryConfigLoaded"}
[2019-05-06 16:32:14 -07:00] GitStatusCacheConfig_Loaded {"Area":"GitStatusCacheConfig","BackOffTime":"00:00:02","Message":"GitStatusCacheConfigLoaded"}
[2019-05-06 16:32:14 -07:00] CachePathsLoaded {"gitObjectsRoot":"C:\\.gvfsCache\\fd98e3a239ab46abb3ba60192ab2c46a\\gitObjects","localCacheRoot":"C:\\.gvfsCache","blobSizesRoot":"C:\\.gvfsCache\\fd98e3a239ab46abb3ba60192ab2c46a\\blobSizes"}
[2019-05-06 16:32:14 -07:00] Mount_StartedNamedPipe {"NamedPipeName":"GVFS_C_\\REPOS\\FORTESTS"}
[2019-05-06 16:32:14 -07:00] AttemptAnonymousAuth (Start)
[2019-05-06 16:32:15 -07:00] Error {"RepoUrl":"https://gvfs.visualstudio.com/ci/_git/ForTests","ErrorMessage":"Failed to parse credential string for approval"}
[2019-05-06 16:32:15 -07:00] NetworkResponse {"RequestId":1,"availableConnections":8,"CacheName":"","StatusCode":200,"ContentType":"application/json; charset=utf-8","connectionWaitTimeMS":"0.0171","responseWaitTimeMS":"326.0839"}
[2019-05-06 16:32:15 -07:00] AttemptAnonymousAuth (Stop) {"HttpStatus":"200","QuerySucceeded":true,"IsAnonymous":true,"DurationMs":812}
[2019-05-06 16:32:15 -07:00] Information {"Message":"Git status cache is not enabled"}
[2019-05-06 16:32:20 -07:00] Error {"ErrorMessage":"Failed to create src folder callback listener Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.\r\n   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)\r\n   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()\r\n   at GVFS.Virtualization.BlobSize.BlobSizes.Initialize()\r\n   at GVFS.Virtualization.FileSystemCallbacks..ctor(GVFSContext context, GVFSGitObjects gitObjects, RepoMetadata repoMetadata, BlobSizes blobSizes, GitIndexProjection gitIndexProjection, BackgroundFileSystemTaskRunner backgroundFileSystemTaskRunner, FileSystemVirtualizer fileSystemVirtualizer, GitStatusCache gitStatusCache)\r\n   at GVFS.Mount.InProcessMount.<>c__DisplayClass33_0.<MountAndStartWorkingDirectoryCallbacks>b__1() in E:\\A\\_work\\685\\s\\GVFS\\GVFS.Mount\\InProcessMount.cs:line 553\r\n   at GVFS.Mount.InProcessMount.CreateOrReportAndExit[T](Func`1 factory, String reportMessage) in E:\\A\\_work\\685\\s\\GVFS\\GVFS.Mount\\InProcessMount.cs:line 218"}
```

**Expected Results**
`gvfs mount` should succeed.

**Other Thoughts**
The failure appears to be related to ACLs.  VFS4G has code for adjusting the ACLs for its repo folders, but the same code is not being run for the .gvfsCache folders:

https://github.com/microsoft/VFSForGit/blob/552323cb0e124580cb72a0c4fd1adc32e7e828e1/GVFS/GVFS.Platform.Windows/WindowsPlatform.cs#L78

Here are the ACLs after the failure:

```
C:\>icacls C:\Repos\ForTests
C:\Repos\ForTests NT AUTHORITY\Authenticated Users:(M)
                  NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(M)
                  NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                  BUILTIN\Administrators:(I)(OI)(CI)(F)
                  BUILTIN\Users:(I)(OI)(CI)(RX)
                  BUILTIN\Users:(I)(CI)(AD)
                  BUILTIN\Users:(I)(CI)(WD)
                  CREATOR OWNER:(I)(OI)(CI)(IO)(F)

Successfully processed 1 files; Failed processing 0 files

C:\>icacls C:\.gvfsCache
C:\.gvfsCache NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
              BUILTIN\Administrators:(I)(OI)(CI)(F)
              BUILTIN\Users:(I)(OI)(CI)(RX)
              BUILTIN\Users:(I)(CI)(AD)
              BUILTIN\Users:(I)(CI)(WD)
              CREATOR OWNER:(I)(OI)(CI)(IO)(F)

Successfully processed 1 files; Failed processing 0 files

C:\>icacls C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a
C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                               BUILTIN\Administrators:(I)(OI)(CI)(F)
                                               BUILTIN\Users:(I)(OI)(CI)(RX)
                                               BUILTIN\Users:(I)(CI)(AD)
                                               BUILTIN\Users:(I)(CI)(WD)
                                               CREATOR OWNER:(I)(OI)(CI)(IO)(F)

Successfully processed 1 files; Failed processing 0 files

C:\>icacls C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes
C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                                         BUILTIN\Administrators:(I)(OI)(CI)(F)
                                                         BUILTIN\Users:(I)(OI)(CI)(RX)
                                                         BUILTIN\Users:(I)(CI)(AD)
                                                         BUILTIN\Users:(I)(CI)(WD)
                                                         CREATOR OWNER:(I)(OI)(CI)(IO)(F)

Successfully processed 1 files; Failed processing 0 files

C:\>icacls C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes\BlobSizes.sql
C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes\BlobSizes.sql NT AUTHORITY\SYSTEM:(I)(F)
                                                                       BUILTIN\Administrators:(I)(F)
                                                                       BUILTIN\Users:(I)(RX)

Successfully processed 1 files; Failed processing 0 files
```

And here are the owners:

```
C:\>dir /q C:\Repos\ForTests
 Volume in drive C is OSDisk
 Volume Serial Number is 6E93-0C3E

 Directory of C:\Repos\ForTests

05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators .
05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators ..
05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators src
               0 File(s)              0 bytes
               3 Dir(s)  227,351,846,912 bytes free

C:\>dir /q C:\.gvfsCache
 Volume in drive C is OSDisk
 Volume Serial Number is 6E93-0C3E

 Directory of C:\.gvfsCache

05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators .
05/06/2019  04:29 PM    <DIR>          NT SERVICE\TrustedInsta..
05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators fd98e3a239ab46abb3ba60192ab2c46a
05/06/2019  04:29 PM               159 BUILTIN\Administrators mapping.dat
               1 File(s)            159 bytes
               3 Dir(s)  227,351,846,912 bytes free

C:\>dir /q C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a
 Volume in drive C is OSDisk
 Volume Serial Number is 6E93-0C3E

 Directory of C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a

05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators .
05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators ..
05/06/2019  04:31 PM    <DIR>          BUILTIN\Administrators blobSizes
05/06/2019  04:29 PM    <DIR>          BUILTIN\Administrators gitObjects
               0 File(s)              0 bytes
               4 Dir(s)  227,351,846,912 bytes free

C:\>dir /q C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes
 Volume in drive C is OSDisk
 Volume Serial Number is 6E93-0C3E

 Directory of C:\.gvfsCache\fd98e3a239ab46abb3ba60192ab2c46a\blobSizes

05/06/2019  04:31 PM    <DIR>          BUILTIN\Administrators .
05/06/2019  04:31 PM    <DIR>          BUILTIN\Administrators ..
05/06/2019  04:29 PM            12,288 BUILTIN\Administrators BlobSizes.sql
05/06/2019  04:31 PM            32,768 BUILTIN\Administrators BlobSizes.sql-shm
05/06/2019  04:31 PM             8,272 BUILTIN\Administrators BlobSizes.sql-wal
               3 File(s)         53,328 bytes
               2 Dir(s)  227,351,846,912 bytes free
```

**Comment by wilbaker** [comment]
@jrbriggs @derrickstolee this ACL issue could also prevent the maintenance tasks from updating their `.time` files.
