### ISSUE TITLE
Non-reproducible Mac Functional Test failures

### ISSUE THREAD

**Issue by pmj** [microsoft/VFSForGit#1204]
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9551320&view=results

I got the 3 failures below on a PR that only touches *unit* tests, nothing that affects functional tests: #1200.

The the tests are all related to renaming, but at this stage #1193 has not been merged yet, which would otherwise be my prime suspect. The failure mode appears to be that the repo is not mounted however, so possibly it has nothing to do at all with renaming.

```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests(GVFS.FunctionalTests.FileSystemRunners.SystemIORunner).GitStatusAfterRenameFileIntoRepo()
  Expected: <empty>
  But was:  "The repo does not appear to be mounted. Use 'gvfs status' to check.
fatal: pre-command hook aborted command
"
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldBeEmpty[T](IEnumerable`1 group, String message) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 13
   at GVFS.FunctionalTests.Tools.GitHelpers.CheckGitCommandAgainstGVFSRepo(String virtualRepoRoot, String command, String[] expectedLinesInResult) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs:line 71
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests.GitStatusAfterRenameFileIntoRepo() in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitMoveRenameTests.cs:line 199

2) Error : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests(GVFS.FunctionalTests.FileSystemRunners.SystemIORunner).GitStatusAfterRenameFileOutOfRepo()
System.IO.FileNotFoundException : Could not find file '/GVFS.FT/test/c9d3762927934bf0922f/src/Test_EPF_MoveRenameFileTests/ChangeUnhydratedFileName/Program.cs'.
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at GVFS.FunctionalTests.FileSystemRunners.SystemIORunner.MoveFile(String sourcePath, String targetPath) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/FileSystemRunners/SystemIORunner.cs:line 21
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests.GitStatusAfterRenameFileOutOfRepo() in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitMoveRenameTests.cs:line 214

3) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests(GVFS.FunctionalTests.FileSystemRunners.SystemIORunner).GitStatusAfterRenameFolderIntoRepo()
  Expected: <empty>
  But was:  "The repo does not appear to be mounted. Use 'gvfs status' to check.
fatal: pre-command hook aborted command
"
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldBeEmpty[T](IEnumerable`1 group, String message) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 13
   at GVFS.FunctionalTests.Tools.GitHelpers.CheckGitCommandAgainstGVFSRepo(String virtualRepoRoot, String command, String[] expectedLinesInResult) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs:line 71
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests.GitStatusAfterRenameFolderIntoRepo() in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitMoveRenameTests.cs:line 241

Run Settings
    Number of Test Workers: 16
    Work Directory: /Users/gvfsadmin/agent/_work/4/s
    Internal Trace: Off
```

**Comment by kewillford** [comment]
Logs have the following error:
```
[2019-05-24 12:37:43 -07:00] Error {"ErrorMessage":"MacFileSystemVirtualizer::OnLogError: MessageType: 10 PrjFSLib.HandleKernelRequest: fsgetpath failed for fsid 0x0:0, inode 0; error = 45(Operation not supported)\n"}
```

**Comment by wilbaker** [comment]
Thanks @kewillford!

@pmj it looks like the client lib received a `MessageType_KtoU_NotifyFileHardLinkCreated` message from the kernel that must have had a null path (and what I am guessing is an invalid `fsid`):

https://github.com/microsoft/VFSForGit/blob/50ef886d3afe886d38c7e2add08b2590f9a3f320/ProjFS.Mac/PrjFSLib/PrjFSLib.cpp#L675
```
    // We expect a non-null request.path for messages sent from the FILEOP handler,
    // whereas messages originating in the kext's vnode handler will only fill
    // the fsid/inode, so we need to look up the path below.
    char pathBuffer[PrjFSMaxPath];
    if (request.paths[MessagePath_Target] == nullptr)
    {
        fsid_t fsid = request.messageHeader->fsidInode.fsid;
        ssize_t pathSize = fsgetpath(pathBuffer, sizeof(pathBuffer), &fsid, request.messageHeader->fsidInode.inode);

        if (pathSize < 0)
        {
            // TODO(Mac): Add this message to PrjFSLib logging once available (#395)
            ostringstream ss;
            ss
                << "MessageType: " << requestHeader->messageType << " "
                << "PrjFSLib.HandleKernelRequest: fsgetpath failed for fsid 0x"
                << hex << fsid.val[0] << ":" << hex << fsid.val[1]
                << ", inode "
                << dec << request.messageHeader->fsidInode.inode
                << "; error = "
                << errno
                << "(" << strerror(errno) << ")"
                << endl;
            string errorMessage = ss.str();
```

I'm thinking it might be due to the code in this scenario:

https://github.com/microsoft/VFSForGit/blob/50ef886d3afe886d38c7e2add08b2590f9a3f320/ProjFS.Mac/PrjFSKext/KauthHandler.cpp#L617
```
            if (messageFromProvider && (!messageTargetProvider || targetRoot != fromRoot)) // Don't send the same message to the same provider twice
            {
                int kauthResult;
                int kauthError = 0;
                if (!ProviderMessaging_TrySendRequestAndWaitForResponse(
                        fromRoot,
                        MessageType_KtoU_NotifyFileHardLinkCreated,
                        // vnode & target path are not in "fromRoot", so don't send them
                        nullptr, // vnode
                        FsidInode{},
                        nullptr, // target path
                        fromPath,
                        pid,
                        procname,
                        &kauthResult,
                        &kauthError))
```

The user-mode lib is assuming that there will always be a valid target path, but it appears that there will not be in this scenario.

@jeschu1 can you confirm that your changes in #1184 will fix this?

**Comment by wilbaker** [comment]
Actually after taking a closer look at the logs it looks like during the failures @pmj mentioned the mount logs mysteriously ended, making me think the GVFS.Mount process crashed or was killed without logging an error:

```
[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41897)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41897)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":315,"LockHeldExternallyMS":315,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}
[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41969)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41969)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":305,"LockHeldExternallyMS":305,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}
[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41897)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41897)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":315,"LockHeldExternallyMS":315,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}
[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41969)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41969)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":305,"LockHeldExternallyMS":305,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}

[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41897)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41897)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":315,"LockHeldExternallyMS":315,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}
[2019-05-24 12:32:29 -07:00] TryAcquireLockExternal {"LockRequest":"git status (41969)","IsElevated":false,"Result":"Accepted"}
[2019-05-24 12:32:29 -07:00] ReleaseExternalLockRequested
[2019-05-24 12:32:29 -07:00] ReleaseLockHeldByExternalProcess {"CurrentLockHolder":"git status (41969)","IsElevated":false,"EnlistmentId":"281b152bb0424c44a4cca619d5b12098","Result":"Released","DurationMS":305,"LockHeldExternallyMS":305,"ParseGitIndexMS":0,"UpdatePlaceholdersMS":0,"UpdateFilePlaceholdersMS":0,"UpdateFolderPlaceholdersMS":0,"DeleteFolderPlacehoderAttempted":0,"PlaceholdersWriteAndFlushMS":0,"ProjectionWriteLockHeldMs":0,"BlobsDownloaded":0,"BlobDownloadTimeMS":0,"CommitsAndTreesDownloaded":0,"CommitsAndTreesDownloadTimeMS":0,"SizeQueries":0,"SizeQueryTimeMS":0}
```

@jeschu1 could you still verify your PR fixes the error that @kewillford found?  Unfortunately I think this issue might be something different than that 😦

**Comment by pmj** [comment]
If `GVFS.Mount` crashed, the machine should have .crash logs in `/Library/Logs/DiagnosticReports/`. Are there any there? (It might be useful to include any files there that appeared there during a test run in the build's log file collection.)

**Comment by wilbaker** [comment]
That's a good idea, I checked `GVFS-MACPRO-2` but didn't see any VFS4G related crashes:

```
GVFS-MACPRO-2:DiagnosticReports gvfsadmin$ ls
Analytics_2019-04-27-173446_GVFS-MACPRO-2.core_analytics
Analytics_2019-04-28-173139_GVFS-MACPRO-2.core_analytics
Analytics_2019-04-29-173135_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-03-173117_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-04-173115_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-05-170815_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-07-173058_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-09-172928_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-10-172915_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-12-172915_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-13-172911_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-14-172815_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-15-170415_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-16-173026_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-17-173013_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-20-172854_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-22-173002_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-25-170015_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-26-173119_GVFS-MACPRO-2.core_analytics
Analytics_2019-05-27-172942_GVFS-MACPRO-2.core_analytics
JetsamEvent_2019-05-18-173145_GVFS-MACPRO-2.jetsam
analyticsd_2019-05-18-173146_GVFS-MACPRO-2.memory_resource.diag
awdd_2019-05-25-045708_GVFS-MACPRO-2.memory_resource.diag
fseventsd_2019-05-10-080447_GVFS-MACPRO-2.memory_resource.diag
installd_2019-04-30-060750_GVFS-MACPRO-2.memory_resource.diag
mds_2019-05-07-120745_GVFS-MACPRO-2.cpu_resource.diag
mdworker_2019-05-01-070657_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-01-141128_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-02-092226_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-03-045027_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-09-100914_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-13-101421_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-14-123047_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-14-211928_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-15-154439_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-17-064039_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-18-015701_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-20-094543_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-20-164726_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-21-193807_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-22-080647_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-22-141828_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-24-102858_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-25-121851_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-27-114713_GVFS-MACPRO-2.memory_resource.diag
mdworker_2019-05-28-030722_GVFS-MACPRO-2.memory_resource.diag
nehelper_2019-05-23-140724_GVFS-MACPRO-2.memory_resource.diag
softwareupdated_2019-05-10-062926_GVFS-MACPRO-2.memory_resource.diag
GVFS-MACPRO-2:DiagnosticReports gvfsadmin$
```

The only other theory that comes to mind right now is that someone/something killed the running mount process, but that seems pretty unlikely.

cc: @jeschu1 @nickgra
