### ISSUE TITLE
Diagnose issues with Functional Tests on Mojave build agent

### ISSUE THREAD

**Issue by nickgra** [microsoft/VFSForGit#1264]
These two tests deterministically fail:
```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasNamedAfterKnownCommandAcquiresLock()
  Expected substring 'Waiting for 'GVFS.FunctionalTests.LockHolder'' not found in ''
  Expected: True
  But was:  False
   at GVFS.Tests.Should.StringShouldExtensions.ShouldContain(String actualValue, String[] expectedSubstrings) in /Users/gvfsadmin/agent/_work/3/s/GVFS/GVFS.Tests/Should/StringShouldExtensions.cs:line 19
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasNamedAfterKnownCommandAcquiresLock() in /Users/gvfsadmin/agent/_work/3/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitReadAndGitLockTests.cs:line 69

2) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasInSubfolderNamedAfterKnownCommandAcquiresLock()
  Expected substring 'Waiting for 'GVFS.FunctionalTests.LockHolder'' not found in 'error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
'
  Expected: True
  But was:  False
   at GVFS.Tests.Should.StringShouldExtensions.ShouldContain(String actualValue, String[] expectedSubstrings) in /Users/gvfsadmin/agent/_work/3/s/GVFS/GVFS.Tests/Should/StringShouldExtensions.cs:line 19
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasInSubfolderNamedAfterKnownCommandAcquiresLock() in /Users/gvfsadmin/agent/_work/3/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitReadAndGitLockTests.cs:line 84
```

See: https://mseng.visualstudio.com/AzureDevOps/_build/results?buildId=9667762

**Comment by nickgra** [comment]
@jrbriggs I believe this is important enough to put into the M155 bucket so I've done so. Please re-prioritize if you disagree.
