### ISSUE TITLE
Reduce error/exception noise by having maintenance tasks check if the repo exists before running

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1447]
We just saw the following error in the `PackfileMaintenanceStep`.

This *could* be due to someone deleting their repo while VFS4G is still mounted.

Rather than having this situation reported as an error, the maintenance task could check that if the repo's folder exists before trying to open it, and if it does not, it could shut the mount process down.

```
System.IO.InvalidDataException: Couldn't open repo at E:\latest\src: could not find repository from 'E:\latest\src'
 at GVFS.Common.Git.LibGit2Repo..ctor(ITracer tracer, String repoPath)
 at GVFS.Common.Git.GitRepo.<.ctor>b__5_0()
 at GVFS.Common.Git.LibGit2RepoInvoker.GetSharedRepo()
 at GVFS.Common.Git.LibGit2RepoInvoker.InitializeSharedRepo()
 at GVFS.Common.Maintenance.PackfileMaintenanceStep.PerformMaintenance()
 at GVFS.Common.Maintenance.GitMaintenanceStep.CreateProcessAndRun()
 at GVFS.Common.Maintenance.GitMaintenanceStep.Execute()
```

**Comment by derrickstolee** [comment]
@wilbaker: [the `GitMaintenanceQueue` already blocks on this](https://github.com/microsoft/VFSForGit/blob/master/GVFS/GVFS.Common/Maintenance/GitMaintenanceQueue.cs#L61). These errors are coming due to a race condition: the user deleted the repo after the step started.

How much do we want to dig in here? Put a check around the LibGit2RepoInvoker? Around GitProcess?

**Comment by wilbaker** [comment]
I think we can make the code a bit smarter about when it decides to call `RelatedError` to reduce the noise we're seeing.
