### ISSUE TITLE
NullReferenceExceptions are sometimes occurring during enumeration

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#145]
```
System.NullReferenceException: Object reference not set to an instance of an object.
 at GVFS.Platform.Windows.ActiveEnumeration.MoveNext() in E:\A\_work\68\s\GVFS\GVFS.Platform.Windows\ActiveEnumeration.cs:line 69
 at GVFS.Platform.Windows.WindowsFileSystemVirtualizer.GetDirectoryEnumerationHandler(Guid enumerationId, String filterFileName, Boolean restartScan, DirectoryEnumerationResults results) in E:\A\_work\68\s\GVFS\GVFS.Platform.Windows\WindowsFileSystemVirtualizer.cs:line 496
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
 at GVFS.Platform.Windows.ActiveEnumeration.MoveNext() in E:\A\_work\68\s\GVFS\GVFS.Platform.Windows\ActiveEnumeration.cs:line 69
 at GVFS.Platform.Windows.ActiveEnumeration.SaveFilter(String filter) in E:\A\_work\68\s\GVFS\GVFS.Platform.Windows\ActiveEnumeration.cs:line 126
 at GVFS.Platform.Windows.WindowsFileSystemVirtualizer.GetDirectoryEnumerationHandler(Guid enumerationId, String filterFileName, Boolean restartScan, DirectoryEnumerationResults results) in E:\A\_work\68\s\GVFS\GVFS.Platform.Windows\WindowsFileSystemVirtualizer.cs:line 473
```
It appears that the ActiveEnumeration is being disposed while it is still in use.

**Comment by wilbaker** [comment]
Fixed in upcoming release
