### ISSUE TITLE
Unhandled exception with gvfs sparse -a xxx

### ISSUE THREAD

**Issue by judemars** [microsoft/VFSForGit#1459]
D:\onew2\src>gvfs sparse -a xxx
Running git status...Failed

On branch `<branch scrubbed>`
Your branch is up to date with `<branch scrubbed>`.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

`<untracked filenames scrubbed>`

nothing added to commit but untracked files present (use "git add" to track)

git status reported that you have dirty files
Either commit your changes or reset and clean
sparse was aborted
GVFS.CommandLine.GVFSVerb+VerbAbortedException: Exception of type 'GVFS.CommandLine.GVFSVerb+VerbAbortedException' was thrown.
   at GVFS.CommandLine.GVFSVerb.ReportErrorAndExit(ITracer tracer, ReturnCode exitCode, String error, Object[] args) in E:\A\_work\655\s\GVFS\GVFS\CommandLine\GVFSVerb.cs:line 304
   at GVFS.CommandLine.SparseVerb.CheckGitStatus(ITracer tracer, GVFSEnlistment enlistment) in E:\A\_work\655\s\GVFS\GVFS\CommandLine\SparseVerb.cs:line 223
   at GVFS.CommandLine.SparseVerb.Execute(GVFSEnlistment enlistment) in E:\A\_work\655\s\GVFS\GVFS\CommandLine\SparseVerb.cs:line 113

**Comment by wilbaker** [comment]
@kewillford FYI - This is happening because of this exception handling in SparseVerb:

https://github.com/microsoft/VFSForGit/blob/f358148053a12cde26e0424c6d4b982dbb935721/GVFS/GVFS/CommandLine/SparseVerb.cs#L151

```
                catch (Exception e)
                {
                    this.ReportErrorAndExit(tracer, e.ToString());
                }
```

`CheckGitStatus` is calling `ReportErrorAndExit` and `ReportErrorAndExit` throws a `VerbAbortedException` exception which is then caught by the above `catch (Exception e)` and the full stack is written to the console.

**Comment by judemars** [comment]
I don't see this anymore - thanks!
