### ISSUE TITLE
Mac: Ensure that the kext blocks file I\O that that is not allowed when VFSForGit is unmounted

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#182]
We *used* to have this on Mac, but it had to be removed in #191 as it was preventing:

- VFS4G from modifying the .git/hooks a as part of mounting
- `gvfs repair` from being able to fix up files in the .git folder

As the feature is re-enabled we'll need to consider how we can still support the scenarios above.  Perhaps we can support a new xattr that VFS4G sets on folders letting the kext know that offline modifications are allowed?  Or maybe there is some way that we can ACL/mark the VFS4G processes so that the kext knows that they should be allowed to make offline modifications?

**Comment by pmj** [comment]
> Or maybe there is some way that we can ACL/mark the VFS4G processes so that the kext knows that they should be allowed to make offline modifications?

Can we have these processes, or at least a parent process of these processes register with the kext? From the kext's point of view, this is going to be the easiest method: any process wanting to modify offline roots needs to open a connection to the kext. We can either create a new `IOUserClient` subclass for this, or possibly roll it into the "provider" client subclass - for example we could start allowing offline modifications from provider `IOServiceOpen()` onwards, before registering as a provider with a path. If the process doesn't actually need to become a provider, it just stays in this state until it's done (`IOServiceClose()` or process exits).

If it is helpful, we can also allow entire process hierarchies to modify offline roots, in a similar way to how we check if a process was spawned by a user by walking up the parent process chain.

**Comment by wilbaker** [comment]
> Can we have these processes, or at least a parent process of these processes register with the kext? 

We could have these processes register with the kext.  In both the cases called out in the description:

- VFS4G from modifying the .git/hooks a as part of mounting
- `gvfs repair` from being able to fix up files in the .git folder

We own the code and I don't think it would be a big deal for the process to make a call to register itself.

>  If the process doesn't actually need to become a provider, it just stays in this state until it's done (IOServiceClose() or process exits).

There are no plans to have these processes become providers.  They might launch the provider process as part of doing their work, but we could have them unregister with the kext before doing so (in case that simplifies anything).

CC: @kewillford as FYI and to double check my statements on provider/process lifetimes

**Comment by wilbaker** [comment]
> If it is helpful, we can also allow entire process hierarchies to modify offline roots, in a similar way to how we check if a process was spawned by a user by walking up the parent process chain.

We *might* need these, I'll have to check if `gvfs repair` launches any child processes.

**Comment by pmj** [comment]
> We could have these processes register with the kext. In both the cases called out in the description:
> 
> * VFS4G from modifying the .git/hooks a as part of mounting
> * `gvfs repair` from being able to fix up files in the .git folder
> 
> We own the code and I don't think it would be a big deal for the process to make a call to register itself.

Sounds good! Can you or someone else point me at the code where I'd need to insert the registration?

> There are no plans to have these processes become providers. They might launch the provider process as part of doing their work, but we could have them unregister with the kext before doing so (in case that simplifies anything).

OK, sounds like there's no point lumping it in with the provider user client. I'll create a new user client class for this purpose then, unless there's some other suggestion for how to identify the processes in question?

**Comment by wilbaker** [comment]
> Can you or someone else point me at the code where I'd need to insert the registration? 

Here is the `Main` method shared by all of the `gvfs <verb>` binaries:

https://github.com/microsoft/VFSForGit/blob/6cf59a9772fe5dde6261d346f14d6a017c7ea27e/GVFS/GVFS/Program.cs#L13

I think it would make sense to add a `RegisterWithKernel` type method to [`IKernelDriver`](https://github.com/microsoft/VFSForGit/blob/master/GVFS/GVFS.Common/FileSystem/IKernelDriver.cs) that would be a no-op on everywhere except in [`ProjFSKext.cs`](https://github.com/microsoft/VFSForGit/blob/master/GVFS/GVFS.Platform.Mac/ProjFSKext.cs).

We could then call that method (`GVFSPlatform.Instance.KernelDriver.RegisterWithKernel()`) after the call to `GVFSPlatformLoader.Initialize()` in `Main`.

We'll also need [some Managed <-> native glue](https://github.com/microsoft/VFSForGit/blob/master/ProjFS.Mac/PrjFSLib.Mac.Managed/Interop/PrjFSLib.cs) to get the call through to PrjFSLib, but that should be pretty minor.

> I'll create a new user client class for this purpose then, unless there's some other suggestion for how to identify the processes in question?

I think that sounds good.  Any sort of "smarts" (e.g. identifying allowed processes via name) are probably more fragile/brittle than simply allowing our processes to register and allowing our processes and their children to make modifications.

**Comment by pmj** [comment]
> I think that sounds good. Any sort of "smarts" (e.g. identifying allowed processes via name) are probably more fragile/brittle than simply allowing our processes to register and allowing our processes and their children to make modifications.

Agreed. Other options I can think of are bundle identifier and code signing identity, but those are likely more complex and make things unnecessarily tricky for anyone using self-compiled versions of VFS4G.

We're not circumventing any normal security mechanisms with this, so I think having processes simply opt-in to write access without any kind of central authorisation is fine.

The simplest approach will be to opt-in globally for all virtualisation roots at once, but in principle we could make it a per-root thing. Opinions on that?

**Comment by wilbaker** [comment]
>The simplest approach will be to opt-in globally for all virtualisation roots at once, but in principle we could make it a per-root thing. Opinions on that?

I think we can go with the simpler approach.  

We've not had the need to restrict access to pre-root in the offline scenarios on Windows, and so there's no need to add that complexity on Mac if we've not identified scenarios that require it.

**Comment by pmj** [comment]
I've got pretty far with implementing this (#1208) but I'm running into some additional problems caused by denying the file I/O operations. During `gvfs mount` it seems that a `git` process wants to create and write to the `src/.git/index` file - this is evidently before the mount has got far enough to register the provider. I was under the impression we generally don't want to allow creating new files in offline roots, but this evidently violates that.

I've re-enabled file creation in offline roots for now (so `gvfs mount` succeeds), and I am now hitting a bunch of test failures which are not obvious to me so I might have some more questions once I have an idea of what's going wrong.

**Comment by pmj** [comment]
I've started enabling "deny" opportunities one by one, and when I deny *write* access to all files in an offline root (bd8be1e), I end up with 4 test failures. Fully detailed failure log is at the bottom of this comment, but the tests are:

 * `GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptGitConfig`
 * `GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSha`
 * `GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSymRef`
 * `GVFS.FunctionalTests.Tests.EnlistmentPerFixture.MountTests.MountRegeneratesAlternatesFileWhenMissingGitObjectsRoot`

Not entirely surprisingly, these tests try to write to various files in the `.git` directory of an offline root, and are being denied access. I'm assuming we need to grant access to the processes that are trying to do this I/O. I don't know the internals of VFS4G userspace or git itself well enough to know where to start looking. Is this git itself that needs to access these files? Is it being spawned by a `gvfs` process so we could inherit the whitelisting from there?

Thanks!

(P.S. #1208 is already a fairly involved PR, and while denying *write* access only results in a relatively small number of test failures, denying *read* access to empty files causes a pretty large number of failures. So resolving this issue entirely might take some considerable additional effort in terms of whitelisting etc. Given that what I've got in #1208 up to and including commit b33039d works fine and doesn't cause any test failures, could we merge that partial implementation of #182 while we turn our attention elsewhere and then return to it some weeks later? I hate leaving PRs to grow stale.)

```
2019-06-07T21:32:42.5927110Z Errors, Failures and Warnings
2019-06-07T21:32:42.5927140Z 
2019-06-07T21:32:42.5927190Z 1) Error : GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptGitConfig()
2019-06-07T21:32:42.5927930Z System.UnauthorizedAccessException : Access to the path '/GVFS.FT/test/0e0a29696175453eb7f4/src/.git/config' is denied.
2019-06-07T21:32:42.5928580Z   ----> System.IO.IOException : Permission denied
2019-06-07T21:32:42.5928680Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-06-07T21:32:42.5928740Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-06-07T21:32:42.5928820Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-06-07T21:32:42.5928890Z    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2019-06-07T21:32:42.5928950Z    at System.IO.File.WriteAllText(String path, String contents)
2019-06-07T21:32:42.5929030Z    at GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptGitConfig() in /Users/gvfsadmin/agent/_work/9/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/RepairTests.cs:line 145
2019-06-07T21:32:42.5929670Z --IOException
2019-06-07T21:32:42.5929730Z 
2019-06-07T21:32:42.5929960Z 2) Error : GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSha()
2019-06-07T21:32:42.5930730Z System.UnauthorizedAccessException : Access to the path '/GVFS.FT/test/400bdc4acf234da2a793/src/.git/HEAD' is denied.
2019-06-07T21:32:42.5931410Z   ----> System.IO.IOException : Permission denied
2019-06-07T21:32:42.5931500Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-06-07T21:32:42.5931570Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-06-07T21:32:42.5931640Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-06-07T21:32:42.5931700Z    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2019-06-07T21:32:42.5931770Z    at System.IO.File.WriteAllText(String path, String contents)
2019-06-07T21:32:42.5931850Z    at GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSha() in /Users/gvfsadmin/agent/_work/9/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/RepairTests.cs:line 29
2019-06-07T21:32:42.5932490Z --IOException
2019-06-07T21:32:42.5932530Z 
2019-06-07T21:32:42.5932590Z 3) Error : GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSymRef()
2019-06-07T21:32:42.5933320Z System.UnauthorizedAccessException : Access to the path '/GVFS.FT/test/74489ad1a139448e9889/src/.git/HEAD' is denied.
2019-06-07T21:32:42.5933980Z   ----> System.IO.IOException : Permission denied
2019-06-07T21:32:42.5934060Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-06-07T21:32:42.5934120Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-06-07T21:32:42.5934190Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-06-07T21:32:42.5934270Z    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2019-06-07T21:32:42.5934320Z    at System.IO.File.WriteAllText(String path, String contents)
2019-06-07T21:32:42.5934400Z    at GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.RepairTests.FixesCorruptHeadSymRef() in /Users/gvfsadmin/agent/_work/9/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/RepairTests.cs:line 43
2019-06-07T21:32:42.5935250Z --IOException
2019-06-07T21:32:42.5935290Z 
2019-06-07T21:32:42.5935360Z 4) Error : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.MountTests.MountRegeneratesAlternatesFileWhenMissingGitObjectsRoot()
2019-06-07T21:32:42.5936090Z System.UnauthorizedAccessException : Access to the path '/GVFS.FT/test/96a0561cd5f04e989298/src/.git/objects/info/alternates' is denied.
2019-06-07T21:32:42.5936740Z   ----> System.IO.IOException : Permission denied
2019-06-07T21:32:42.5936830Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-06-07T21:32:42.5936900Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-06-07T21:32:42.5936980Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-06-07T21:32:42.5937050Z    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2019-06-07T21:32:42.5937110Z    at System.IO.File.WriteAllText(String path, String contents)
2019-06-07T21:32:42.5937190Z    at GVFS.FunctionalTests.FileSystemRunners.SystemIORunner.WriteAllText(String path, String contents) in /Users/gvfsadmin/agent/_work/9/s/GVFS/GVFS.FunctionalTests/FileSystemRunners/SystemIORunner.cs:line 106
2019-06-07T21:32:42.5937280Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.MountTests.MountRegeneratesAlternatesFileWhenMissingGitObjectsRoot() in /Users/gvfsadmin/agent/_work/9/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/MountTests.cs:line 203
2019-06-07T21:32:42.5938100Z --IOException
```

**Comment by wilbaker** [comment]
> Not entirely surprisingly, these tests try to write to various files in the .git directory of an offline root, and are being denied access.  I'm assuming we need to grant access to the processes that are trying to do this I/O. I don't know the internals of VFS4G userspace or git itself well enough to know where to start looking. Is this git itself that needs to access these files? Is it being spawned by a gvfs process so we could inherit the whitelisting from there?

@pmj as you've pointed out the issue is the test process itself trying to write to the .git directory when the provider is offline.

@jeschu1 or I can update the functional test process to call `RegisterForOfflineIO` and `DeregisterForOfflineIO` as needed.  I think it makes sense to branch for us to branch from bd8be1e
 and make the changes there.

I'm thinking all we'll need to do is:

- Add the DllImports to the functional test code for register/deregister (the tests don't consume VFS4G product code directly)
- In the setup/teardown for the failing test fixtures call `RegisterForOfflineIO` and `DeregisterForOfflineIO` (when running on Mac)

@jeschu1 do you have bandwidth to pick this up this sprint?  If not I can try to pick it up when I have some cycles available.

> denying read access to empty files causes a pretty large number of failures

I think it makes sense to defer the blocking empty read work to a follow up issue and PR.  It's more important that we prevent users from modifying files when VFS4G is unmounted as `git status` might miss those changes if VFS4G is not mounted and detecting them.

/cc: @jrbriggs

**Comment by jeschu1** [comment]
@pmj I added a commit to register/unregister to the functional tests and they are now green here https://github.com/microsoft/VFSForGit/pull/1208.

Let us know when the PR is ready for a review :-)

**Comment by pmj** [comment]
As pointed out by @jeschu1 while reviewing #1208, we haven't actually specified anywhere what should and should not be blocked. My understanding is the following:

 * At a high level, the goals are:
   * To ensure the provider does not miss any messages that might cause it to lose track of code changes.
   * To prevent reading incorrect data from unhydrated files.
 * Specifically, this means we need to intercept and block file I/O when:
   * A message failed to deliver to the provider.
   * A process attempts to write to an empty file (this file would subsequently be overwritten by a hydration event)
   * A process attempts to write to a placeholder (hydrated unmodified) file. The file would not show up in `git status` and could be overwritten by a subsequent checkout/rebase/merge.
   * A process attempts to read/execute an empty file. The result of the read would be bad data, so failing with denied authorisation is preferable to letting the bad data propagate.

Does that sound right?

**Comment by wilbaker** [comment]
> Does that sound right? 

All the scenarios you mentioned sound right to me.  

> Anything I've missed?

Ideally we'd block these as well:

- Delete operations that are for renames (i.e. moving a file out of the offline repo)
- Moving files into the offline repo (not sure if we'd get a KAUTH_VNODE_ADD_FILE for this)
- Mode changes to placeholders (both empty and hydrated) in the offline root.  Note that we still have #457 to detect mode changes in the first place, and so we might not be able to add that check now.

I don't think any of the above actions should hold up #1208 or completing this work item.  We can file follow up work item(s) for any remaining scenarios.

**Comment by pmj** [comment]
PR #1208 implements a large part of the functionality required for this task, but we still have the following I/O left to block in an offline root:

 * A process attempts to read/execute an empty file in an offline root. The result of the read would be bad data, so failing with denied authorisation is preferable to letting the bad data propagate.
 * A process attempts to create files or directories in an offline root.

**Comment by wilbaker** [comment]
@pmj are you aware of any remaining work for this issue or can we close it out?

**Comment by pmj** [comment]
With #1429 done, there's now not much left to do here. A few loose ends:

> [@wilbaker]
> Ideally we'd block these as well:
> 
> * Delete operations that are for renames (i.e. moving a file out of the offline repo)

This is now implemented for *empty* files. I *think* that's what we want: we already allow deleting files for other reasons than renaming, and I think it's reasonable to allow a user to move hydrated or full files out of the repo, possibly in order to back up some work they did before deleting the repo entirely.

> * Moving files into the offline repo (not sure if we'd get a KAUTH_VNODE_ADD_FILE for this)

We do indeed get a callback with that action, or `KAUTH_VNODE_ADD_SUBDIRECTORY` if the thing being moved is a directory, and both are now blocked on offline roots as of #1429.

> * Mode changes to placeholders (both empty and hydrated) in the offline root.  Note that we still have #457 to detect mode changes in the first place, and so we might not be able to add that check now.

I think this will be a case of blocking `KAUTH_VNODE_WRITE_SECURITY` when offline, but I'd have to check - and yes, I'd agree, let's cover that as part of #457.

**Comment by wilbaker** [comment]
@pmj thanks!

I think we can close this out.

Regarding this item:

> Delete operations that are for renames (i.e. moving a file out of the offline repo)

I think we can stick with the current behavior and adjust it later if we get feedback that the current behavior is undesirable.

> I'd agree, let's cover that as part of #457.

I've updated the description of #457 to include this work.
