### ISSUE TITLE
ForceCheckoutRequiresCheckout test fails

### ISSUE THREAD

**Issue by jamill** [Microsoft/VFSForGit#185]
**Test failure logs:**
```
2018-08-17T02:06:15.5470876Z 1) Failed : GVFS.FunctionalTests.Tests.FastFetchTests.ForceCheckoutRequiresCheckout()
2018-08-17T02:06:15.5471137Z   Expected: 0
2018-08-17T02:06:15.5471330Z   But was:  1
2018-08-17T02:06:15.5471883Z    at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in C:\agent\_work\4\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 34
2018-08-17T02:06:15.5472355Z    at GVFS.FunctionalTests.Tests.FastFetchTests.RunFastFetch(String args) in C:\agent\_work\4\s\GVFS\GVFS.FunctionalTests\Tests\FastFetchTests.cs:line 496
2018-08-17T02:06:15.5472804Z    at GVFS.FunctionalTests.Tests.FastFetchTests.ForceCheckoutRequiresCheckout() in C:\agent\_work\4\s\GVFS\GVFS.FunctionalTests\Tests\FastFetchTests.cs:line 145
```

**Failed Builds:**
[18229.1](https://gvfs.visualstudio.com/ci/_build/results?buildId=552&view=logs)

**Comment by jrbriggs** [comment]
@kyle-rader can you please take a look at this test flakiness?

**Comment by sanoursa** [comment]
This is a reliable failure, not intermittent or flaky. The test case is calling a method that expects the fastfetch verb to succeed, even though the test is explicitly running a command that will fail. @kyle-rader please rework this test ASAP to make it pass.

@kewillford why did this make it through our build policy? Looking in the PR (https://github.com/Microsoft/VFSForGit/pull/159), Kyle ran the full tests and they show success in the PR, but when you click through to the report (https://gvfs.visualstudio.com/ci/_build/results?buildId=551&view=logs) it shows that the test actually failed there too.
