### ISSUE TITLE
Upgrade Microsoft.Data.Sqlite to prevent System.InvalidOperationException: SqliteConnection does not support nested transactions.

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#273]
The issue described here:

https://github.com/aspnet/Microsoft.Data.Sqlite/issues/532

could be causing the occasional SQLite related exception we've been seeing:

```
System.InvalidOperationException: SqliteConnection does not support nested transactions.
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at GVFS.Virtualization.BlobSize.BlobSizes.BlobSizesDatabaseWriter.TryAddSizes(ConcurrentQueue`1 sizes, Int32& errorCode, String& error)
   at GVFS.Virtualization.BlobSize.BlobSizes.FlushDbThreadMain()\",\"ErrorMessage\":\"FlushDbThreadMain caught unhandled exception, exiting process\"}"
```

If there is an internal rollback without the [fix mentioned above](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/532) `SqliteTransaction.Complete()` will *not* be called leaving a non-null `Transaction` set on `BlobSizesDatabaseWriter.connection`

We should pick up the fix and see if the issue persists.

**Comment by jeschu1** [comment]
We're waiting on 2.2.0 [here](https://www.nuget.org/packages/Microsoft.Data.SQLite/2.2.0) to get out of preview
