### ISSUE TITLE
ArgumentOutOfRangeException when parsing index at mount

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#290]
From internal telemetry, I see a couple of failures here:
```
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at GVFS.Virtualization.Projection.GitIndexProjection.GitIndexParser.PerformIndexAction(GitIndexProjection projection, FileStream indexFileStream, IndexAction action)
   at GVFS.Virtualization.Projection.GitIndexProjection.ReadIndex(String indexPath)
   at GVFS.CommandLine.MountVerb.PerformPreMountValidation(ITracer tracer, GVFSEnlistment enlistment, String& mountExeLocation, String& errorMessage) in E:\A\_work\45\s\GVFS\GVFS\CommandLine\MountVerb.cs:line 269
```

**Comment by kewillford** [comment]
There has been only 2 of these by the same user on the same machine in the last 30 days and is usually the result of a corrupt index.  Index is corrupted by a BSOD if there is a git command that updates the index that is being ran when it happens.  I will repro this and see what the message to the user is and if we can help them become unblocked by running `gvfs repair`

**Comment by kewillford** [comment]
The user will get a good message letting them know what to do to fix this.
```
C:\gvfs_repos\GVFS>gvfs mount
Authenticating...Succeeded
Querying remote for config...Succeeded
Configured cache server: None (https://mseng@dev.azure.com/mseng/AzureDevOps/_git/_full/GVFS)
Validating repo...Failed. Run 'gvfs log C:\gvfs_repos\GVFS' for more info.
Index validation failed, run 'gvfs repair' to repair index.
```
