### ISSUE TITLE
SharedCacheTests.SecondCloneSucceedsWithMissingTrees is flaky: permissions on delete?

### ISSUE THREAD

**Issue by derrickstolee** [Microsoft/VFSForGit#330]
I got the following error in a functional test build that I didn't see while working on #313 

```
Error : GVFS.FunctionalTests.Tests.MultiEnlistmentTests.SharedCacheTests.SecondCloneSucceedsWithMissingTrees()
System.UnauthorizedAccessException : Access to the path 'C:\Repos\GVFSFunctionalTests\f06935dd64a74c2e8ff1593944aa3860\.customGvfsCache2\1491ffe944734853883aa7dd7c20bfec\gitObjects\pack\pack-3baad044a78f454e83efdbd65f9a0ed4.idx' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at GVFS.FunctionalTests.FileSystemRunners.SystemIORunner.DeleteFile(String path) in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\FileSystemRunners\SystemIORunner.cs:line 52
   at GVFS.FunctionalTests.Tests.MultiEnlistmentTests.SharedCacheTests.SecondCloneSucceedsWithMissingTrees() in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\Tests\MultiEnlistmentTests\SharedCacheTests.cs:line 284
```

It seems that someone is holding a handle to a pack-file while we are trying to delete it. Probably the multi-pack-index writer.

**Comment by derrickstolee** [comment]
See #331 which removes the test to avoid blocking others.
