### ISSUE TITLE
LockToPreventUpdate_MultipleFiles test fails occasionally

### ISSUE THREAD

**Issue by kewillford** [Microsoft/VFSForGit#379]
This tests seems to be flaky since it will fail occasionally.

GVFS.FunctionalTests.Tests.EnlistmentPerFixture.WindowsUpdatePlaceholderTests.LockToPreventUpdate_MultipleFiles

Failure was:
System.IO.IOException : The process cannot access the file 'C:\Repos\GVFSFunctionalTests\enlistment\16e733ff76ff49b5b457\.gvfs\databases\ModifiedPaths.dat' because it is being used by another process.

**Comment by sanoursa** [comment]
@kewillford do you have more of the call stack or the logs from the test? Was this exception in the test code or in the product code?

**Comment by kewillford** [comment]
In the test code

Full callstack:
```
2018-10-12T16:19:11.4331843Z System.IO.IOException : The process cannot access the file 'C:\Repos\GVFSFunctionalTests\enlistment\16e733ff76ff49b5b457\.gvfs\databases\ModifiedPaths.dat' because it is being used by another process.
2018-10-12T16:19:11.4332471Z    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2018-10-12T16:19:11.4333008Z    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2018-10-12T16:19:11.4333563Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2018-10-12T16:19:11.4333945Z    at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
2018-10-12T16:19:11.4334369Z    at GVFS.FunctionalTests.Tools.GVFSHelpers.ReadAllTextFromWriteLockedFile(String filename) in C:\agent\_work\12\s\GVFS\GVFS.FunctionalTests\Tools\GVFSHelpers.cs:line 99
2018-10-12T16:19:11.4335238Z    at GVFS.FunctionalTests.Tools.GVFSHelpers.ModifiedPathsShouldContain(FileSystemRunner fileSystem, String dotGVFSRoot, String[] gitPaths) in C:\agent\_work\12\s\GVFS\GVFS.FunctionalTests\Tools\GVFSHelpers.cs:line 116
2018-10-12T16:19:11.4335872Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.WindowsUpdatePlaceholderTests.LockToPreventUpdate_MultipleFiles() in C:\agent\_work\12\s\GVFS\GVFS.FunctionalTests.Windows\Windows\Tests\WindowsUpdatePlaceholderTests.cs.cs:line 232
```

**Comment by sanoursa** [comment]
@kewillford @wilbaker Is it possible that the test is racing with the rename+overwrite in the product code? When the product code opens a handle to the file, it allows read sharing, but I don't know if the same applies when it does a rename over the top of an existing file.

If that is correct, then perhaps the test just needs to retry a couple of times?

**Comment by wilbaker** [comment]
@sanoursa that's a good theory.  @kewillford, I'm wondering if `ModifiedPathsShouldContain` should have this line in it:

```
this.Enlistment.WaitForBackgroundOperations().ShouldEqual(true, "Background operations failed to complete.");
```
That would ensure the BG tasks have finished updating ModifiedPaths, and it should eliminate the race mentioned by @sanoursa.

Thoughts?

**Comment by kewillford** [comment]
@wilbaker Yes that sounds like the right fix to me.
