### ISSUE TITLE
PrefetchVerbTests.PrefetchCleansUpStalePrefetchLock fails intermittently

### ISSUE THREAD

**Issue by nickgra** [Microsoft/VFSForGit#380]
While refactoring code to light up 'prefetch --hydrate', I noticed that on Windows, this test fail intermittently. I have only seen it fail when the other LockHolder tests are failing (see #176), but often the LockHolder tests will fail without it.

See https://gvfs.visualstudio.com/ci/_build/results?buildId=2617&view=logs for one sample:

```
2018-10-12T12:36:50.1053529Z Errors, Failures and Warnings
2018-10-12T12:36:50.1060127Z 
2018-10-12T12:36:50.1060828Z 1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasNamedAfterKnownCommandAcquiresLock()
2018-10-12T12:36:50.1061496Z   Expected substring 'Waiting for 'GVFS.FunctionalTests.LockHolder'' not found in ''
2018-10-12T12:36:50.1061932Z   Expected: True
2018-10-12T12:36:50.1062282Z   But was:  False
2018-10-12T12:36:50.1062896Z    at GVFS.Tests.Should.StringShouldExtensions.ShouldContain(String actualValue, String[] expectedSubstrings) in C:\agent\_work\2\s\GVFS\GVFS.Tests\Should\StringShouldExtensions.cs:line 19
2018-10-12T12:36:50.1064058Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasNamedAfterKnownCommandAcquiresLock() in C:\agent\_work\2\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GitReadAndGitLockTests.cs:line 71
2018-10-12T12:36:50.1064701Z 
2018-10-12T12:36:50.1065616Z 2) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasInSubfolderNamedAfterKnownCommandAcquiresLock()
2018-10-12T12:36:50.1066354Z   Expected substring 'Waiting for 'GVFS.FunctionalTests.LockHolder'' not found in 'error: Failed to merge in the changes.
2018-10-12T12:36:50.1066862Z '
2018-10-12T12:36:50.1067173Z   Expected: True
2018-10-12T12:36:50.1067573Z   But was:  False
2018-10-12T12:36:50.1068218Z    at GVFS.Tests.Should.StringShouldExtensions.ShouldContain(String actualValue, String[] expectedSubstrings) in C:\agent\_work\2\s\GVFS\GVFS.Tests\Should\StringShouldExtensions.cs:line 19
2018-10-12T12:36:50.1069507Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitReadAndGitLockTests.GitAliasInSubfolderNamedAfterKnownCommandAcquiresLock() in C:\agent\_work\2\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GitReadAndGitLockTests.cs:line 87
2018-10-12T12:36:50.1070032Z 
2018-10-12T12:36:50.1070496Z 3) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.PrefetchVerbTests.PrefetchCleansUpStalePrefetchLock()
2018-10-12T12:36:50.1070925Z   Expected: 0
2018-10-12T12:36:50.1071238Z   But was:  128
2018-10-12T12:36:50.1071798Z    at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in C:\agent\_work\2\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 34
2018-10-12T12:36:50.1072635Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.PrefetchVerbTests.PostFetchJobShouldComplete() in C:\agent\_work\2\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\PrefetchVerbTests.cs:line 143
2018-10-12T12:36:50.1073499Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.PrefetchVerbTests.PrefetchCleansUpStalePrefetchLock() in C:\agent\_work\2\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\PrefetchVerbTests.cs:line 113
```

**Comment by wilbaker** [comment]
Happened here too:

https://gvfs.visualstudio.com/ci/_build/results?buildId=7220

I have retained that build.

**Comment by jamill** [comment]
The latest issue appears to be different than the original reported issue. In the most recent occurrence has the following error:

```
=> GVFS.FunctionalTests.Tests.EnlistmentPerFixture.PrefetchVerbTests.PrefetchCleansUpStalePrefetchLock()
Test GVFS.FunctionalTests.Tests.EnlistmentPerFixture.PrefetchVerbTests.PrefetchCleansUpStalePrefetchLock()
Failed at 4:10:16 PM taking 00:00:03.1008981
  C:\Repos\GVFSFunctionalTests\enlistment\..\.gvfsCache is expected to have only one folder. Actual folders: C:\Repos\GVFSFunctionalTests\.gvfsCache\29988cba39514a77bf35068f41600402,C:\Repos\GVFSFunctionalTests\.gvfsCache\b810a5d8b978423bb9fe3aa140499e0e
  Expected: 1
  But was:  2
```

It looks like a functional test was run that targeted a different remote repository, which had a different .GVFS cache directory:

https://gvfs.visualstudio.com/ci/_build/results?buildId=7199

```"Remote":"https://github.com/Microsoft/VFSForGit.git", "localCacheKey":"29988cba39514a77bf35068f41600402"```

**Comment by jamill** [comment]
The latest issue should be addressed by: #845
