### ISSUE TITLE
Wrap error "The device is not ready." in a proper error and exit

### ISSUE THREAD

**Issue by jeschu1** [microsoft/VFSForGit#463]
We see the below error coming thru telementry.  It should be wrapped in a proper exception wrapper and exit.

Unhandled exception in connection handler

System.IO.IOException: The device is not ready.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Flush(Boolean flushToDisk)

**Comment by wilbaker** [comment]
@jeschu1 is this the full call stack?
