### ISSUE TITLE
Mount Failure when Status Cache can't run

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#489]
Perhaps we should issue a warning and not take down the process when Status Cache can't run?

MountId - a3d2edc96e50439eb28592076419bd1f

System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\o1\.gvfs\gitStatusCache'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at GVFS.Common.GitStatusCache.TryRebuildStatusCache()
   at GVFS.Common.GitStatusCache.RebuildStatusCacheIfNeeded(Boolean ignoreBackoff)
   at GVFS.Common.GitStatusCache.SerializeStatusMainThread()

**Comment by jeschu1** [comment]
As dicussed offline the affected user switched his drive from G to D.  This isn't supported in VFS.  

Up to you if you want to make the StatusCache more bulletproof or punt the bug since we know it's an unsupported scenario.

**Comment by jeschu1** [comment]
Thinking about this more if we were going to do anything here, i'd vote for checking if the drive changed on startup and have a error message there we can filter in telemetry.  So far I've seen two users change their drive letter and when that happens it would be great to filter that out as potential bugs on our side since the feature is unsupported.
