### ISSUE TITLE
DiagnoseTests.DiagnoseProducesZipFile fails intermittently due to sharing violation

### ISSUE THREAD

**Issue by nickgra** [Microsoft/VFSForGit#558]
I've only seen this once in many functional test runs so it seems to be quite intermittent.

https://gvfs.visualstudio.com/ci/_build/results?buildId=4193

```
2018-11-28T04:01:24.7923783Z 1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.DiagnoseTests.DiagnoseProducesZipFile()
2018-11-28T04:01:24.7923986Z   Unexpected substring 'Failed' found in 'Collecting diagnostic info into temp folder C:\Repos\GVFSFunctionalTests\enlistment\f531da41d1264c95998d\.gvfs\diagnostics\gvfs_20181128_023224
2018-11-28T04:01:24.7924116Z 
2018-11-28T04:01:24.7924185Z gvfs version 0.2.18332.1
2018-11-28T04:01:24.7924364Z git version 2.19.1.gvfs.1.3
2018-11-28T04:01:24.7924471Z C:\Program Files\Git\cmd\git.exe
2018-11-28T04:01:24.7924517Z 
2018-11-28T04:01:24.7924597Z Enlistment root: C:\Repos\GVFSFunctionalTests\enlistment\f531da41d1264c95998d
2018-11-28T04:01:24.7924724Z Cache Server: https://gvfs.visualstudio.com/ci/_git/ForTests
2018-11-28T04:01:24.7924819Z Local Cache: C:\Repos\GVFSFunctionalTests\.gvfsCache
2018-11-28T04:01:24.7924871Z 
2018-11-28T04:01:24.7924980Z Available space on C:\ drive(enlistment and local cache): 65.02 GB
2018-11-28T04:01:24.7925035Z 
2018-11-28T04:01:24.7925286Z 
2018-11-28T04:01:24.7925381Z Unmounting...-
2018-11-28T04:01:24.7925425Z Unmounting...\
2018-11-28T04:01:24.7925485Z Unmounting...\
2018-11-28T04:01:24.7925622Z Unmounting...|
2018-11-28T04:01:24.7925684Z Unmounting...|
2018-11-28T04:01:24.7925900Z Unmounting.../
2018-11-28T04:01:24.7925940Z Unmounting.../
2018-11-28T04:01:24.7926185Z Unmounting...-
2018-11-28T04:01:24.7926227Z Unmounting...Succeeded
2018-11-28T04:01:24.7926276Z 
2018-11-28T04:01:24.7926939Z Copying logs...-
2018-11-28T04:01:24.7927000Z Copying logs...\
2018-11-28T04:01:24.7927078Z Copying logs...\
2018-11-28T04:01:24.7927183Z Copying logs...|Failed to copy 'repo-registry.lock' in C:\ProgramData\GVFS\Test.GVFS.Service with exception System.IO.IOException: The process cannot access the file 'C:\ProgramData\GVFS\Test.GVFS.Service\repo-registry.lock' because it is being used by another process.
2018-11-28T04:01:24.7927317Z    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2018-11-28T04:01:24.7927407Z    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
2018-11-28T04:01:24.7927553Z    at GVFS.CommandLine.DiagnoseVerb.RecursiveFileCopyImpl(String sourcePath, String targetPath, Boolean copySubFolders, Boolean hideErrorsFromStdout) in C:\agent\_work\8\s\GVFS\GVFS\CommandLine\DiagnoseVerb.cs:line 403
2018-11-28T04:01:24.7927644Z 
2018-11-28T04:01:24.7927696Z Copying logs...Succeeded
2018-11-28T04:01:24.7927729Z 
2018-11-28T04:01:24.7927805Z Mounting...-
2018-11-28T04:01:24.7927873Z Mounting...\
2018-11-28T04:01:24.7927999Z Mounting...\
2018-11-28T04:01:24.7928095Z Mounting...|
2018-11-28T04:01:24.7928191Z Mounting...|
2018-11-28T04:01:24.7928339Z Mounting.../
2018-11-28T04:01:24.7928432Z Mounting.../
2018-11-28T04:01:24.7928563Z Mounting...-
2018-11-28T04:01:24.7928617Z Mounting...-
2018-11-28T04:01:24.7928689Z Mounting...\
2018-11-28T04:01:24.7928740Z Mounting...\
2018-11-28T04:01:24.7928790Z Mounting...|
2018-11-28T04:01:24.7928876Z Mounting...|
2018-11-28T04:01:24.7928925Z Mounting.../
2018-11-28T04:01:24.7928998Z Mounting.../
2018-11-28T04:01:24.7929056Z Mounting...-
2018-11-28T04:01:24.7929132Z Mounting...-
2018-11-28T04:01:24.7929182Z Mounting...\
2018-11-28T04:01:24.7929231Z Mounting...\
2018-11-28T04:01:24.7929305Z Mounting...|
2018-11-28T04:01:24.7929354Z Mounting...|
2018-11-28T04:01:24.7929428Z Mounting.../
2018-11-28T04:01:24.7929477Z Mounting.../
2018-11-28T04:01:24.7929551Z Mounting...-
2018-11-28T04:01:24.7929602Z Mounting...-
2018-11-28T04:01:24.7929652Z Mounting...\
2018-11-28T04:01:24.7929725Z Mounting...\
2018-11-28T04:01:24.7929775Z Mounting...|
2018-11-28T04:01:24.7929849Z Mounting...|
2018-11-28T04:01:24.7930063Z Mounting.../
2018-11-28T04:01:24.7930316Z Mounting.../
2018-11-28T04:01:24.7930354Z Mounting...-
2018-11-28T04:01:24.7930390Z Mounting...-
2018-11-28T04:01:24.7930448Z Mounting...\
2018-11-28T04:01:24.7930484Z Mounting...\
2018-11-28T04:01:24.7930542Z Mounting...|
2018-11-28T04:01:24.7930584Z Mounting...|
2018-11-28T04:01:24.7930690Z Mounting.../
2018-11-28T04:01:24.7930729Z Mounting.../
2018-11-28T04:01:24.7930793Z Mounting...-
2018-11-28T04:01:24.7930829Z Mounting...-
2018-11-28T04:01:24.7930887Z Mounting...\
2018-11-28T04:01:24.7930924Z Mounting...\
2018-11-28T04:01:24.7930960Z Mounting...|
2018-11-28T04:01:24.7931018Z Mounting...|
2018-11-28T04:01:24.7931054Z Mounting.../
2018-11-28T04:01:24.7931115Z Mounting.../
2018-11-28T04:01:24.7931151Z Mounting...-
2018-11-28T04:01:24.7931209Z Mounting...-
2018-11-28T04:01:24.7931246Z Mounting...\
2018-11-28T04:01:24.7931282Z Mounting...\
2018-11-28T04:01:24.7931340Z Mounting...|
2018-11-28T04:01:24.7931376Z Mounting...|
2018-11-28T04:01:24.7931435Z Mounting.../
2018-11-28T04:01:24.7931474Z Mounting.../
2018-11-28T04:01:24.7931532Z Mounting...-
2018-11-28T04:01:24.7931568Z Mounting...-
2018-11-28T04:01:24.7931604Z Mounting...\
2018-11-28T04:01:24.7931662Z Mounting...\
2018-11-28T04:01:24.7931698Z Mounting...|
2018-11-28T04:01:24.7931881Z Mounting...|
2018-11-28T04:01:24.7931917Z Mounting.../
2018-11-28T04:01:24.7931977Z Mounting.../
2018-11-28T04:01:24.7932085Z Mounting...-
2018-11-28T04:01:24.7932122Z Mounting...-
2018-11-28T04:01:24.7932183Z Mounting...\
2018-11-28T04:01:24.7932219Z Mounting...\
2018-11-28T04:01:24.7932278Z Mounting...|
2018-11-28T04:01:24.7932314Z Mounting...|
2018-11-28T04:01:24.7932372Z Mounting.../
2018-11-28T04:01:24.7932408Z Mounting.../
2018-11-28T04:01:24.7932445Z Mounting...-
2018-11-28T04:01:24.7932503Z Mounting...-
2018-11-28T04:01:24.7932539Z Mounting...\
2018-11-28T04:01:24.7932598Z Mounting...\
2018-11-28T04:01:24.7932635Z Mounting...|
2018-11-28T04:01:24.7932692Z Mounting...|
2018-11-28T04:01:24.7932729Z Mounting.../
2018-11-28T04:01:24.7932765Z Mounting.../
2018-11-28T04:01:24.7932823Z Mounting...-
2018-11-28T04:01:24.7932860Z Mounting...-
2018-11-28T04:01:24.7932918Z Mounting...\
2018-11-28T04:01:24.7932954Z Mounting...\
2018-11-28T04:01:24.7933011Z Mounting...|
2018-11-28T04:01:24.7933054Z Mounting...|
2018-11-28T04:01:24.7933089Z Mounting.../
2018-11-28T04:01:24.7933148Z Mounting...Succeeded
2018-11-28T04:01:24.7933178Z 
2018-11-28T04:01:24.7933239Z Creating zip file...-
2018-11-28T04:01:24.7933279Z Creating zip file...\
2018-11-28T04:01:24.7933318Z Creating zip file...\
2018-11-28T04:01:24.7933378Z Creating zip file...|
2018-11-28T04:01:24.7933417Z Creating zip file...|
2018-11-28T04:01:24.7933477Z Creating zip file.../
2018-11-28T04:01:24.7933515Z Creating zip file.../
2018-11-28T04:01:24.7933574Z Creating zip file...-
2018-11-28T04:01:24.7933613Z Creating zip file...-
2018-11-28T04:01:24.7933651Z Creating zip file...\
2018-11-28T04:01:24.7933710Z Creating zip file...\
2018-11-28T04:01:24.7933748Z Creating zip file...|
2018-11-28T04:01:24.7933807Z Creating zip file...|
2018-11-28T04:01:24.7933845Z Creating zip file.../
2018-11-28T04:01:24.7933903Z Creating zip file.../
2018-11-28T04:01:24.7933941Z Creating zip file...-
2018-11-28T04:01:24.7934007Z Creating zip file...-
2018-11-28T04:01:24.7934044Z Creating zip file...\
2018-11-28T04:01:24.7934082Z Creating zip file...\
2018-11-28T04:01:24.7934151Z Creating zip file...|
2018-11-28T04:01:24.7934189Z Creating zip file...|
2018-11-28T04:01:24.7934248Z Creating zip file.../
2018-11-28T04:01:24.7934286Z Creating zip file.../
2018-11-28T04:01:24.7934345Z Creating zip file...-
2018-11-28T04:01:24.7934383Z Creating zip file...-
2018-11-28T04:01:24.7934421Z Creating zip file...\
2018-11-28T04:01:24.7934482Z Creating zip file...\
2018-11-28T04:01:24.7934520Z Creating zip file...Succeeded
2018-11-28T04:01:24.7934567Z 
2018-11-28T04:01:24.7934614Z Diagnostics complete. All of the gathered info, as well as all of the output above, is captured in
2018-11-28T04:01:24.7934672Z C:\Repos\GVFSFunctionalTests\enlistment\f531da41d1264c95998d\.gvfs\diagnostics\gvfs_20181128_023224.zip
2018-11-28T04:01:24.7934739Z '
2018-11-28T04:01:24.7934775Z   Expected: False
2018-11-28T04:01:24.7934836Z   But was:  True
2018-11-28T04:01:24.7934910Z    at GVFS.Tests.Should.StringShouldExtensions.ShouldNotContain(String actualValue, Boolean ignoreCase, String[] unexpectedSubstrings) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\StringShouldExtensions.cs:line 35
2018-11-28T04:01:24.7935021Z    at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.DiagnoseTests.DiagnoseProducesZipFile() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\DiagnoseTests.cs:line 26
2018-11-28T04:01:24.7935062Z 
```

**Comment by wilbaker** [comment]
This should be fixed by https://github.com/Microsoft/VFSForGit/pull/776/commits/afa15bf935d02c3b667aec896b3edb58a2f39af2 in #776 and #777
