### ISSUE TITLE
Sporadic failure in ModifiedPathsTest

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#589]
Got a random failure in this test, and it passed on the next run:

https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=7917214
```
2018-12-06T00:06:27.5219490Z 1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.ModifiedPathsTests.DeletedTempFolderDeletesFilesFromModifiedFiles(GVFS.FunctionalTests.FileSystemRunners.BashRunner)
2018-12-06T00:06:27.5219590Z   Unexpected matching entry found in {A Temp/,A .gitattributes,}
2018-12-06T00:06:27.5219670Z   Expected: null
2018-12-06T00:06:27.5219730Z   But was:  "A Temp/"
2018-12-06T00:06:27.5219830Z    at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.Tests/Should/ValueShouldExtensions.cs:line 34
2018-12-06T00:06:27.5220220Z    at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldNotContain[T](IEnumerable`1 group, Func`2 predicate) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 51
2018-12-06T00:06:27.5220380Z    at GVFS.FunctionalTests.Tools.GVFSHelpers.ModifiedPathsShouldNotContain(GVFSFunctionalTestEnlistment enlistment, FileSystemRunner fileSystem, String[] gitPaths) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tools/GVFSHelpers.cs:line 127
2018-12-06T00:06:27.5220760Z    at GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.ModifiedPathsTests.DeletedTempFolderDeletesFilesFromModifiedFiles(FileSystemRunner fileSystem) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/ModifiedPathsTests.cs:line 74
```

**Comment by derrickstolee** [comment]
I got this on the CI builds, too: [Build 8070626](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8070626)

**Comment by wilbaker** [comment]
I also hit this on a CI build: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8434968
