### ISSUE TITLE
Failure in RebaseWithDirectoryNameSameAsFileWithWrite

### ISSUE THREAD

**Issue by jamill** [Microsoft/VFSForGit#790]
[Test failures](https://gvfs.visualstudio.com/ci/_build/results?buildId=6951&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&taskId=5552b382-64d1-58e8-ad13-103a0d4e23a9&lineStart=49391&lineEnd=49450&colStart=1&colEnd=111)

```
 1-1) Failed : GVFS.FunctionalTests.Tests.GitCommands.RebaseTests(True).RebaseWithDirectoryNameSameAsFileWithWrite()
checkout FunctionalTests/20180214 Errors Lines
checkout FunctionalTests/20180214 Errors Lines counts do not match. was: 2 expected: 1
Extra: The repo does not appear to be mounted. Use 'gvfs status' to check.
Extra: fatal: pre-command hook aborted command
Missing: Already on 'FunctionalTests/20180214'
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in C:\agent\_work\11\s\GVFS\GVFS.Tests\Should\EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ErrorsShouldMatch(String command, ProcessResult expectedResult, ProcessResult actualResult) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 157
   at GVFS.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(GVFSFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 108
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.ValidateGitCommand(String command, Object[] args) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 205
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.SetupForTest() in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 84
```

```
1-2) Failed : GVFS.FunctionalTests.Tests.GitCommands.RebaseTests(True).RebaseWithDirectoryNameSameAsFileWithWrite()
status Errors Lines
status Errors Lines counts do not match. was: 2 expected: 0
Extra: The repo does not appear to be mounted. Use 'gvfs status' to check.
Extra: fatal: pre-command hook aborted command
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in C:\agent\_work\11\s\GVFS\GVFS.Tests\Should\EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ErrorsShouldMatch(String command, ProcessResult expectedResult, ProcessResult actualResult) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 157
   at GVFS.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(GVFSFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 108
   at GVFS.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(GVFSFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 114
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.ValidateGitCommand(String command, Object[] args) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 205
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.CheckHeadCommitTree() in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 166
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TestValidationAndCleanup(Boolean ignoreCase) in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 107
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TearDownForTest() in C:\agent\_work\11\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 100
```

**Comment by jrbriggs** [comment]
@jamill looking at the logs, it looks like the service was unhealthy

```
2019-02-14T15:37:55.2367355Z ----- C:\Repos\GVFSFunctionalTests\enlistment\8cb2cff057264b8f8872\.gvfs\logs\gvfs_mount_process_20190214_153512.log -----
2019-02-14T15:37:55.2367850Z [2019-02-14 15:35:12 +00:00] GVFSMount (Start) {"Version":"0.2.19045.6","EnlistmentRoot":"C:\\Repos\\GVFSFunctionalTests\\enlistment\\8cb2cff057264b8f8872","Remote":"https://gvfs.visualstudio.com/ci/_git/ForTests","ObjectsEndpoint":"https://gvfs.visualstudio.com/ci/_git/ForTests","IsElevated":true,"EnlistmentRootPathParameter":"C:\\Repos\\GVFSFunctionalTests\\enlistment\\8cb2cff057264b8f8872","StartedByService":"False"}
2019-02-14T15:37:55.2368091Z [2019-02-14 15:35:13 +00:00] RetryConfig_LoadedRetryConfig {"Area":"RetryConfig","Timeout":"00:00:30","MaxRetries":6,"Message":"RetryConfigLoaded"}
2019-02-14T15:37:55.2368232Z [2019-02-14 15:35:13 +00:00] GitStatusCacheConfig_Loaded {"Area":"GitStatusCacheConfig","BackOffTime":"00:00:02","Message":"GitStatusCacheConfigLoaded"}
2019-02-14T15:37:55.2368474Z [2019-02-14 15:35:13 +00:00] CachePathsLoaded {"gitObjectsRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache\\b810a5d8b978423bb9fe3aa140499e0e\\gitObjects","localCacheRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache","blobSizesRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache\\b810a5d8b978423bb9fe3aa140499e0e\\blobSizes"}
2019-02-14T15:37:55.2368662Z [2019-02-14 15:35:13 +00:00] Mount_StartedNamedPipe {"NamedPipeName":"GVFS_C_\\REPOS\\GVFSFUNCTIONALTESTS\\ENLISTMENT\\8CB2CFF057264B8F8872"}
2019-02-14T15:37:55.2368781Z [2019-02-14 15:35:13 +00:00] AttemptAnonymousAuth (Start)
2019-02-14T15:37:55.2368906Z [2019-02-14 15:35:16 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0095","responseWaitTimeMS":"2342.7220"}
2019-02-14T15:37:55.2369068Z [2019-02-14 15:35:19 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0016","responseWaitTimeMS":"2825.8774"}
2019-02-14T15:37:55.2369424Z [2019-02-14 15:35:24 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"1503.1858"}
2019-02-14T15:37:55.2369719Z [2019-02-14 15:35:35 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"2804.5114"}
2019-02-14T15:37:55.2369972Z [2019-02-14 15:35:55 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"2804.4760"}
2019-02-14T15:37:55.2370134Z [2019-02-14 15:36:27 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0024","responseWaitTimeMS":"2805.4003"}
2019-02-14T15:37:55.2370295Z [2019-02-14 15:37:35 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0011","responseWaitTimeMS":"2806.2327"}
2019-02-14T15:37:55.2370458Z [2019-02-14 15:37:35 +00:00] AttemptAnonymousAuth (Stop) {"HttpStatus":"503","QuerySucceeded":false,"IsAnonymous":false,"DurationMs":141526}
2019-02-14T15:37:55.2370587Z [2019-02-14 15:37:35 +00:00] Error {"ErrorMessage":"Failed to obtain git credentials: Unable to determine if authentication is required"}
```

**Comment by wilbaker** [comment]
@jamill, @jrbriggs  looks like the mount failed in that test due to an authorization error.  

We were getting 503s back, and mount will fail if we can't initialize `GitAuthentication`

```
2019-02-14T15:37:55.2367355Z ----- C:\Repos\GVFSFunctionalTests\enlistment\8cb2cff057264b8f8872\.gvfs\logs\gvfs_mount_process_20190214_153512.log -----
2019-02-14T15:37:55.2367850Z [2019-02-14 15:35:12 +00:00] GVFSMount (Start) {"Version":"0.2.19045.6","EnlistmentRoot":"C:\\Repos\\GVFSFunctionalTests\\enlistment\\8cb2cff057264b8f8872","Remote":"https://gvfs.visualstudio.com/ci/_git/ForTests","ObjectsEndpoint":"https://gvfs.visualstudio.com/ci/_git/ForTests","IsElevated":true,"EnlistmentRootPathParameter":"C:\\Repos\\GVFSFunctionalTests\\enlistment\\8cb2cff057264b8f8872","StartedByService":"False"}
2019-02-14T15:37:55.2368091Z [2019-02-14 15:35:13 +00:00] RetryConfig_LoadedRetryConfig {"Area":"RetryConfig","Timeout":"00:00:30","MaxRetries":6,"Message":"RetryConfigLoaded"}
2019-02-14T15:37:55.2368232Z [2019-02-14 15:35:13 +00:00] GitStatusCacheConfig_Loaded {"Area":"GitStatusCacheConfig","BackOffTime":"00:00:02","Message":"GitStatusCacheConfigLoaded"}
2019-02-14T15:37:55.2368474Z [2019-02-14 15:35:13 +00:00] CachePathsLoaded {"gitObjectsRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache\\b810a5d8b978423bb9fe3aa140499e0e\\gitObjects","localCacheRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache","blobSizesRoot":"C:\\Repos\\GVFSFunctionalTests\\.gvfsCache\\b810a5d8b978423bb9fe3aa140499e0e\\blobSizes"}
2019-02-14T15:37:55.2368662Z [2019-02-14 15:35:13 +00:00] Mount_StartedNamedPipe {"NamedPipeName":"GVFS_C_\\REPOS\\GVFSFUNCTIONALTESTS\\ENLISTMENT\\8CB2CFF057264B8F8872"}
2019-02-14T15:37:55.2368781Z [2019-02-14 15:35:13 +00:00] AttemptAnonymousAuth (Start)
2019-02-14T15:37:55.2368906Z [2019-02-14 15:35:16 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0095","responseWaitTimeMS":"2342.7220"}
2019-02-14T15:37:55.2369068Z [2019-02-14 15:35:19 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0016","responseWaitTimeMS":"2825.8774"}
2019-02-14T15:37:55.2369424Z [2019-02-14 15:35:24 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"1503.1858"}
2019-02-14T15:37:55.2369719Z [2019-02-14 15:35:35 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"2804.5114"}
2019-02-14T15:37:55.2369972Z [2019-02-14 15:35:55 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0013","responseWaitTimeMS":"2804.4760"}
2019-02-14T15:37:55.2370134Z [2019-02-14 15:36:27 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0024","responseWaitTimeMS":"2805.4003"}
2019-02-14T15:37:55.2370295Z [2019-02-14 15:37:35 +00:00] NetworkResponse {"RequestId":1,"availableConnections":4,"CacheName":"","StatusCode":503,"connectionWaitTimeMS":"0.0011","responseWaitTimeMS":"2806.2327"}
2019-02-14T15:37:55.2370458Z [2019-02-14 15:37:35 +00:00] AttemptAnonymousAuth (Stop) {"HttpStatus":"503","QuerySucceeded":false,"IsAnonymous":false,"DurationMs":141526}
2019-02-14T15:37:55.2370587Z [2019-02-14 15:37:35 +00:00] Error {"ErrorMessage":"Failed to obtain git credentials: Unable to determine if authentication is required"}
```

**Comment by wilbaker** [comment]
@jrbriggs you beat me to it.

**Comment by jrbriggs** [comment]
I think we did all we could to successfully run this test. I'm closing this issue. These sporadic failures are something we'll accept to run against the live service.
