### ISSUE TITLE
Mac Flaky test: ModifiedPathsTests.DeletedTempFileIsRemovedFromModifiedFiles

### ISSUE THREAD

**Issue by nickgra** [Microsoft/VFSForGit#808]
I just kicked off some Functional Tests in a loop and we hit this functional test failure.
It looks similar to #419

I've retained the build:
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8491493&_a=summary

```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.ModifiedPathsTests.DeletedTempFileIsRemovedFromModifiedFiles(GVFS.FunctionalTests.FileSystemRunners.BashRunner)
  Unexpected matching entry found in {A .gitattributes,A temp.txt,}
  Expected: null
  But was:  "A temp.txt"
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in /Users/gvfsadmin/agent/_work/7/s/GVFS/GVFS.Tests/Should/ValueShouldExtensions.cs:line 34
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldNotContain[T](IEnumerable`1 group, Func`2 predicate) in /Users/gvfsadmin/agent/_work/7/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 51
   at GVFS.FunctionalTests.Tools.GVFSHelpers.ModifiedPathsShouldNotContain(GVFSFunctionalTestEnlistment enlistment, FileSystemRunner fileSystem, String[] gitPaths) in /Users/gvfsadmin/agent/_work/7/s/GVFS/GVFS.FunctionalTests/Tools/GVFSHelpers.cs:line 127
   at GVFS.FunctionalTests.Tests.EnlistmentPerTestCase.ModifiedPathsTests.DeletedTempFileIsRemovedFromModifiedFiles(FileSystemRunner fileSystem) in /Users/gvfsadmin/agent/_work/7/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/ModifiedPathsTests.cs:line 50
```

**Comment by nickgra** [comment]
@kewillford Can you take an initial look at this since it looks so similar to #419.
