### ISSUE TITLE
Make sure Maitenance jobs shut down cleanly

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#821]
In telemetry I see
WarningMessage": "PostFetchMaintenanceStep: Not launching Git process because the mount is stopping"

followed by
System.NullReferenceException: Object reference not set to an instance of an object.
   at GVFS.Common.Maintenance.PostFetchStep.PerformMaintenance()
   at GVFS.Common.Maintenance.GitMaintenanceStep.CreateProcessAndRun()
   at GVFS.Common.Maintenance.GitMaintenanceStep.Execute()

The thought is that we're trying to do something on a object that is now null.   Unfortunately no line numbers are given.  

Further improvements would be to log in telemetry when we get an Unmount event.

MountId: 05085813f25f41969e015796d208ca3c for reference

**Comment by jeschu1** [comment]
I believe this is the source of the error:

```
      protected GitProcess.Result RunGitCommand(Func<GitProcess, GitProcess.Result> work)
        {
            using (ITracer activity = this.Context.Tracer.StartActivity("RunGitCommand", EventLevel.Informational, Keywords.Telemetry, metadata: this.CreateEventMetadata()))
            {
                if (this.Stopping)
                {
                    this.Context.Tracer.RelatedWarning(
                        metadata: null,
                        message: this.Area + ": Not launching Git process because the mount is stopping",
                        keywords: Keywords.Telemetry);

                    return null;
                }
```

in PostFetchStep
```
                GitProcess.Result verifyResult = this.RunGitCommand((process) => process.VerifyMultiPackIndex(this.Context.Enlistment.GitObjectsRoot));
                if (verifyResult.ExitCodeIsFailure)

```
