### ISSUE TITLE
CreateFileWithoutClose tests failed in Mac CI build

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#847]
Failing tests were added in #734

```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.GitCommands.StatusTests(False).CreateFileWithoutClose()
status Output Lines
status Output Lines counts do not match. was: 2 expected: 5
Extra: nothing to commit, working tree clean
Missing: Untracked files:
Missing:   (use "git add <file>..." to include in what will be committed)
Missing: 	CreateFileWithoutClose.md
Missing: nothing added to commit but untracked files present (use "git add" to track)
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(GVFSFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs:line 109
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.ValidateGitCommand(String command, Object[] args) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitRepoTests.cs:line 205
   at GVFS.FunctionalTests.Tests.GitCommands.StatusTests.CreateFileWithoutClose() in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tests/GitCommands/StatusTests.cs:line 46

2) Failed : GVFS.FunctionalTests.Tests.GitCommands.StatusTests(True).CreateFileWithoutClose()
status Output Lines
status Output Lines counts do not match. was: 2 expected: 5
Extra: nothing to commit, working tree clean
Missing: Untracked files:
Missing:   (use "git add <file>..." to include in what will be committed)
Missing: 	CreateFileWithoutClose.md
Missing: nothing added to commit but untracked files present (use "git add" to track)
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.Tests/Should/EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(GVFSFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs:line 109
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.ValidateGitCommand(String command, Object[] args) in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitRepoTests.cs:line 205
   at GVFS.FunctionalTests.Tests.GitCommands.StatusTests.CreateFileWithoutClose() in /Users/gvfsadmin/agent/_work/5/s/GVFS/GVFS.FunctionalTests/Tests/GitCommands/StatusTests.cs:line 46

```

https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8581014

(Build has been marked for retention)

**Comment by wilbaker** [comment]
@nickgra it looks like the build did not upload any kext logs, could you take a look?

**Comment by wilbaker** [comment]
@jeschu1 @jrbriggs FYI - I put this in the "macOS Early Adopters" Milestone because that's where #734 was bucketed.  This is the first time I've seen this test fail.

**Comment by nickgra** [comment]
@wilbaker Apologies for the trouble, this was broken when we moved to installing the product as part of the Functional Tests. I've updated the task group to run the kext log upload and uninstallation even if the tests fail.

**Comment by jeschu1** [comment]
Thanks @wilbaker i'll keep an eye out.  I know there are certain 'rare' conditions where an event could be dropped.  I'm wondering if that is related.  The test itself shouldn't be flakey.

**Comment by jeschu1** [comment]
I just got a repro of this, so definitely bumping the priority on my side
