### ISSUE TITLE
GitMoveRenameTests.GitStatusAfterRenameFileIntoRepo test failed in Mac CI build

### ISSUE THREAD

**Issue by pmj** [Microsoft/VFSForGit#890]
I've just had this fail on the functional test run for #887; the changes in that PR can't possibly be causing that failure.

```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests(GVFS.FunctionalTests.FileSystemRunners.SystemIORunner).GitStatusAfterRenameFileIntoRepo()
  Expected substring 'Untracked files:' not found in 'On branch FunctionalTests/20180214
nothing to commit, working tree clean
'
  Expected: True
  But was:  False
   at GVFS.Tests.Should.StringShouldExtensions.ShouldContain(String actualValue, String[] expectedSubstrings) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.Tests/Should/StringShouldExtensions.cs:line 19
   at GVFS.FunctionalTests.Tools.GitHelpers.CheckGitCommandAgainstGVFSRepo(String virtualRepoRoot, String command, String[] expectedLinesInResult) in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs:line 55
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.GitMoveRenameTests.GitStatusAfterRenameFileIntoRepo() in /Users/gvfsadmin/agent/_work/4/s/GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitMoveRenameTests.cs:line 197

Run Settings
    Number of Test Workers: 16
    Work Directory: /Users/gvfsadmin/agent/_work/4/s
    Internal Trace: Off
```

Possibly related to #847, but probably not if this is testing that we're handling a `FILEOP_RENAME` event correctly?

The build is here: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8730781 and I have retained it.

**Comment by wilbaker** [comment]
Added additional logging in #1006 to help diagnose this issue if it happens again.  Closing the issue for now, it can be re-opened if/when the issue hits again.
