### ISSUE TITLE
gvfs upgrade crash

### ISSUE THREAD

**Issue by alameenshah** [Microsoft/VFSForGit#896]
GVFS Version: `1.0.18297.1`

```
C:\Users\corepkg>gvfs upgrade --confirm
Checking for GVFS upgrades...Succeeded
New GVFS version 1.0.19060.1 available in ring Slow
Launching upgrade tool...
 
Installer launched in a new window. Do not run any git or gvfs commands until the installer has completed.
``` 
And then it crashes in the new window:
```
Downloading.../
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GVFS.Common.ProductUpgrader.TryDownloadAsset(Asset asset, String& errorMessage)
   at GVFS.Common.ProductUpgrader.TryDownloadNewestVersion(String& errorMessage)
   at GVFS.Upgrader.UpgradeOrchestrator.TryDownloadUpgrade(Version version, String& consoleError)
   at GVFS.Upgrader.UpgradeOrchestrator.<>c__DisplayClass16_0.<TryRunUpgrade>b__0()
   at GVFS.Common.ConsoleHelper.<>c__DisplayClass1_0.<ShowStatusWhileRunning>b__0()
   at GVFS.Common.ConsoleHelper.ShowStatusWhileRunning(Func`1 action, String message, TextWriter output, Boolean showSpinner, String gvfsLogEnlistmentRoot, Int32 initialDelayMs)
   at GVFS.Upgrader.UpgradeOrchestrator.LaunchInsideSpinner(Func`1 method, String message)
   at GVFS.Upgrader.UpgradeOrchestrator.TryRunUpgrade(Version& newVersion, String& consoleError)
   at GVFS.Upgrader.UpgradeOrchestrator.Execute()
   at GVFS.Upgrader.Program.Main(String[] args)
```

**Comment by alameenshah** [comment]
User is not able to repro. Possibly un-expected Github/Release API response tripping the upgrader. Was able to create a similar crash by manually corrupting Release API response in debugger. `GitHubUpgrader` should validate the JSON response before using it.
