### ISSUE TITLE
System.Runtime.Remoting.RemotingException when using Git

### ISSUE THREAD

**Issue by Nazeehe** [Microsoft/VFSForGit#899]
Hey,

When I checking out branches, I keep getting this error message:

Failed during action Checkout

[EXCEPTION]
System.Runtime.Remoting.RemotingException: Attempt to redirect activation of type 'Enlistment.Manager.IPC.ServiceRPC, Enlistment.Manager' which is already redirected.
   at System.Runtime.Remoting.RemotingConfigHandler.RemotingConfigInfo.AddWellKnownClientType(WellKnownClientTypeEntry entry)
   at System.Runtime.Remoting.RemotingConfiguration.RegisterWellKnownClientType(WellKnownClientTypeEntry entry)
   at Hyperbuild.Core.IPC.RegisterClientType[T](String host, IChannel channel)
   at Enlistment.Manager.IPC.Connection.Connect()
   at Enlistment.Client.Actions.Notifications.Checkout(GitCommitConfig config)

Thoughts?

**Comment by jrbriggs** [comment]
This looks like some internal build system. Moving to an internal email.
