### ISSUE TITLE
CreateFileWithoutClose failure in Windows Full Functional Tests Build

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#945]
One time failure in `CreateFileWithoutClose` on Windows:

```
1) Failed : GVFS.FunctionalTests.Tests.GitCommands.StatusTests(True).CreateFileWithoutClose()
clean -d -f -x Errors Lines
clean -d -f -x Errors Lines counts do not match. was: 0 expected: 1
Missing: warning: failed to remove CreateFileWithoutClose.md: Invalid argument
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ErrorsShouldMatch(String command, ProcessResult expectedResult, ProcessResult actualResult) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 157
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.RunGitCommand(String command, Boolean ignoreErrors, Boolean checkStatus) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 194
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TestValidationAndCleanup(Boolean ignoreCase) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 116
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TearDownForTest() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 100
```

From the summary about it looks like the NTFS git repo might have actually been what had a problem.

Link to build:

https://gvfs.visualstudio.com/ci/_build/results?buildId=8313&view=logs

**NOTE** This build had 2 attempts, the failure is in the logs for the first attempt.

**Comment by jeschu1** [comment]
@wilbaker I ran this test in  loop 1,000 times on the build machine and no failure.

As you suggested I think the issue was specific to the repo.  Closing it down pls let me know if you object.
