### ISSUE TITLE
Failure in WriteWithoutClose in Mac CI Build

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#947]
https://gvfs.visualstudio.com/ci/_build/results?buildId=8333

```
1) Failed : GVFS.FunctionalTests.Tests.GitCommands.StatusTests(False).WriteWithoutClose()
reset --hard -q HEAD Errors Lines
reset --hard -q HEAD Errors Lines counts do not match. was: 0 expected: 2
Missing: error: unable to unlink old 'Readme.md': Invalid argument
Missing: fatal: Could not reset index file to revision 'HEAD'.
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ErrorsShouldMatch(String command, ProcessResult expectedResult, ProcessResult actualResult) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 157
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.RunGitCommand(String command, Boolean ignoreErrors, Boolean checkStatus) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 194
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TestValidationAndCleanup(Boolean ignoreCase) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 115
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TearDownForTest() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 100
```

**Comment by wilbaker** [comment]
Just saw this failure in the Windows Full Functional tests as well:

```
1) Failed : GVFS.FunctionalTests.Tests.GitCommands.StatusTests(False).WriteWithoutClose()
reset --hard -q HEAD Errors Lines
reset --hard -q HEAD Errors Lines counts do not match. was: 0 expected: 2
Missing: error: unable to unlink old 'Readme.md': Invalid argument
Missing: fatal: Could not reset index file to revision 'HEAD'.
   at GVFS.Tests.Should.EnumerableShouldExtensions.ShouldMatchInOrder[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, String message) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\EnumerableShouldExtensions.cs:line 119
   at GVFS.FunctionalTests.Tools.GitHelpers.ErrorsShouldMatch(String command, ProcessResult expectedResult, ProcessResult actualResult) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tools\GitHelpers.cs:line 189
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.RunGitCommand(String command, Boolean ignoreErrors, Boolean checkStatus) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 194
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TestValidationAndCleanup(Boolean ignoreCase) in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 115
   at GVFS.FunctionalTests.Tests.GitCommands.GitRepoTests.TearDownForTest() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\GitCommands\GitRepoTests.cs:line 100
```

https://gvfs.visualstudio.com/ci/_build/results?buildId=8542
