### ISSUE TITLE
Windows: HooksInstaller.InstallHooks sometimes fails during mount verb

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#955]
We've had a three reports of this issue since the release of version 1.0.18297.1:

Two reports of "Failed to flush buffers":
```
Error installing hooks: Failed to copy C:\Program Files\GVFS\GVFS.ReadObjectHook.exe
System.ComponentModel.Win32Exception (0x80004005): Failed to flush buffers for 'F:\<repo name>\src\.git\hooks\read-object.exe.temp'
   at GVFS.Common.NativeMethods.ThrowLastWin32Exception(String message)
   at GVFS.Common.NativeMethods.FlushFileBuffers(String path)
   at GVFS.Common.FileSystem.PhysicalFileSystem.TryCopyToTempFileAndRename(String sourcePath, String destinationPath, Exception& handledException)
```

One report of "Failed to move":
```
e:\git\os\src>gvfs mount
Error installing hooks: Failed to copy GitHooksLoader.exe to E:\git\<repo name>\src\.git\hooks\pre-command.exe
System.ComponentModel.Win32Exception (0x80004005): Failed to move 'E:\git\os\src\.git\hooks\pre-command.exe.temp' to 'E:\git\os\src\.git\hooks\pre-command.exe'
   at GVFS.Common.NativeMethods.ThrowLastWin32Exception(String message)
   at GVFS.Common.NativeMethods.MoveFile(String existingFileName, String newFileName, MoveFileFlags flags)
   at GVFS.Common.FileSystem.PhysicalFileSystem.TryCopyToTempFileAndRename(String sourcePath, String destinationPath, Exception& handledException)
```

Ideally we can root cause and fix this, but at a minimum, we should update VFS4G to provide the user with a more actionable message.

Related issue: #168

**Comment by colin969** [comment]
I see this marked as polish and backlog, but it's consistently preventing our main user from using it so I'm commenting in the hopes that someone might take a look at it. (Tried ~5 times, consistently getting the `Failed to move` error). Can provide diagnostics if necessary, although not sure how to do that with zips in git issues.
